### PR TITLE
prod(webImages): optimizing Images Files

### PR DESCRIPTION
**Pull request by CrookedRadRoach**

### CODE REVIEW

**Comment by steviebeenz** [comment]
Can you please explain exactly what you are doing with these image files. Also, CI tests are failing, use semantic PR names.

**Comment by steviebeenz** [comment]
Thank You for the PR

**Comment by CrookedRadRoach** [comment]
I am only compressing these files through jpegoptim.

**Comment by steviebeenz** [comment]
Thanks for the PR!

**Pull request merged**
